- name: Import vars
  run_once: true
  include_vars:
    file: k8svars.yml
    name: vardata

- name: Download Releasekey  
  become: true
  shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes"
  register: key
- debug:
     msg:
       - "{{ key.stdout }}"

- name: echo to sources list
  become: true
  shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"
  register: list
- debug:
     msg:
       - "{{ list.stdout }}"


- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install kubeadm and kubectl
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - kubeadm
    - kubectl



- name: Set up kubectl for the root user
  become: true
  command: "{{ item }}"
  with_items:
      - "sudo mkdir -p /root/.kube"
      - "sudo chown -R root /root/.kube"
      - "sudo cp /etc/kubeconfig /root/.kube/config"


- name: Download cilium
  ansible.builtin.get_url:
    url: https://github.com/cilium/cilium-cli/releases/download/v0.16.22/cilium-linux-amd64.tar.gz
    dest: /etc/cilium-linux-amd64.tar.gz
    mode: '0440'

- name: Extract cilium.tgz into /usr/local/bin
  ansible.builtin.unarchive:
    src: /etc/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    #remote_src: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/cilium-linux-amd64.tar.gz
    state: absent

- name: install cilium
  shell: "cilium install --set ipam.operator.clusterPoolIPv4PodCIDRList={{ vardata.podnetwork }} --set ipv6.enabled=false"
  register: cilium
- debug:
     msg:
      - "{{ cilium.stdout }}"


- name: Download Helm
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.16.3-linux-amd64.tar.gz
    dest: /etc/helm-v3.16.3-linux-amd64.tar.gz
    mode: '0440'

- name: Extract helm.gz 
  ansible.builtin.unarchive:
    src: /etc/helm-v3.16.3-linux-amd64.tar.gz
    dest: $HOME/
    #remote_src: yes

- name: Remove helm tar file (delete file)
  ansible.builtin.file:
    path: /etc/helm-v3.16.3-linux-amd64.tar.gz
    state: absent

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: $HOME/linux-amd64/
    dest: /usr/local/bin/
    #remote_src: yes

- name: Add traefik repo, create traefik namespace, and install traefik
  become: true
  command: "{{ item }}"
  with_items:
      - "helm repo add traefik https://traefik.github.io/charts"
      - "helm repo update"
      #- "kubectl create ns traefik-v2"
      - "helm install -n kube-system traefik traefik/traefik"


#- name: Install Calico network plugin
#  become: no
#  shell: "kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml"